# Auto-generated by rules_vivado. Sourced by Vivado's embedded tclsh at hook
# time. Resolves the rlocation-style paths written into this wrapper by
# rules_tcl to real filesystem paths, then lappends auto_path and sources
# main. Handles three staging shapes:
#   1. Direct `<self>.runfiles/` sibling directory (wrapper executed as-is)
#   2. `<self>.runfiles_manifest` sibling file (executed with
#      `--nobuild_runfile_links` and no tree materialized)
#   3. Wrapper sourced from INSIDE another action's runfiles tree — the
#      `<self>.runfiles/` sibling doesn't exist because the wrapper is
#      nested. Walk up ancestors to find the enclosing `.runfiles/`
#      directory that DOES exist and treat that as `_rv_tree`.

set _rv_self [file normalize [info script]]
set _rv_tree "${_rv_self}.runfiles"

# Shape 3: enclosing-runfiles fallback. When a `tcl_binary` wrapper is
# passed as a `pre_hooks`/`post_hooks` entry, rules_vivado stages it
# under the CONSUMING action's runfiles tree; the wrapper never runs as
# its own executable, so no `<self>.runfiles/` sibling exists. But the
# outer action's runfiles tree DOES exist as one of our ancestors —
# find it by walking up until we hit a directory whose name ends in
# `.runfiles`. That tree's `_main/…` layout contains the rlocation
# targets we need (main + any tcl_library deps' pkgIndex dirs).
if {![file isdirectory $_rv_tree]} {
    set _rv_probe [file dirname $_rv_self]
    while {$_rv_probe ne "/" && $_rv_probe ne ""} {
        if {[string match *.runfiles [file tail $_rv_probe]]} {
            set _rv_tree $_rv_probe
            break
        }
        set _rv_probe [file dirname $_rv_probe]
    }
    unset _rv_probe
}

# `_rv_rloc_map` maps rlocationpath -> concrete path. Populated from the
# manifest only when no runfiles tree materialized (fallback path).
array set _rv_rloc_map {}
if {![file isdirectory $_rv_tree]} {
    set _rv_manifest "${_rv_self}.runfiles_manifest"
    if {[file exists $_rv_manifest]} {
        set _rv_fh [open $_rv_manifest r]
        while {[gets $_rv_fh _rv_line] >= 0} {
            set _rv_line [string trim $_rv_line]
            if {$_rv_line eq ""} { continue }
            set _rv_sp [string first " " $_rv_line]
            if {$_rv_sp < 0} { continue }
            set _rv_key [string range $_rv_line 0 [expr {$_rv_sp - 1}]]
            set _rv_val [string range $_rv_line [expr {$_rv_sp + 1}] end]
            set _rv_rloc_map($_rv_key) $_rv_val
        }
        close $_rv_fh
        unset _rv_fh _rv_line _rv_sp _rv_key _rv_val
    }
    unset _rv_manifest
}

proc _rv_rloc {rlp} {
    global _rv_rloc_map _rv_tree
    if {[info exists _rv_rloc_map($rlp)]} {
        return $_rv_rloc_map($rlp)
    }
    set _rv_candidate [file join $_rv_tree $rlp]
    if {[file exists $_rv_candidate]} {
        return $_rv_candidate
    }
    error "vivado hook wrapper: cannot resolve rlocationpath: $rlp"
}

# Snapshot `auto_path` so THIS hook's `tcl_library` dep dirs are visible
# only during its own `source [_rv_rloc {main}]`. Vivado sources every
# PRE_HOOKS/POST_HOOKS entry in the same tclsh session; without a
# save/restore, hook A leaves its dep dirs on `auto_path` where hook B
# can transitively `package require` them without declaring the dep.
#
# Caveat: this does NOT isolate Tcl's `package` REGISTRY. A package
# already loaded by an earlier hook stays loaded and remains visible to
# later hooks even if they didn't declare the dep. Full isolation would
# require `package forget` on the load delta or a subinterpreter — both
# have their own issues with Vivado's built-in packages.
set _rv_saved_auto_path $auto_path
foreach _rv_inc {auto_path} {
    lappend auto_path [_rv_rloc $_rv_inc]
}

# Export the wrapper's runfiles tree as `RUNFILES_DIR` for the duration
# of the hook's `source`, so the hook can `package require runfiles;
# runfiles::create` (from `@rules_tcl//tcl/runfiles`) and resolve
# rlocationpaths through the standard API — no dep on the
# wrapper-provided `_rv_rloc` proc. Snapshot the existing value so
# concurrently-sourced hooks in the same Vivado session don't clobber
# each other. Fallback path (`$_rv_tree` not a real directory) skips
# the export so runfiles.tcl's manifest fallback can still fire off
# the wrapper's own `<self>.runfiles_manifest`.
if {[info exists ::env(RUNFILES_DIR)]} {
    set _rv_saved_runfiles_dir $::env(RUNFILES_DIR)
} else {
    set _rv_saved_runfiles_dir ""
}
set _rv_had_runfiles_dir [info exists ::env(RUNFILES_DIR)]
if {[file isdirectory $_rv_tree]} {
    set ::env(RUNFILES_DIR) $_rv_tree
}

set _rv_source_status [catch {source [_rv_rloc {main}]} _rv_source_err _rv_source_opts]

if {$_rv_had_runfiles_dir} {
    set ::env(RUNFILES_DIR) $_rv_saved_runfiles_dir
} else {
    unset -nocomplain ::env(RUNFILES_DIR)
}
unset _rv_saved_runfiles_dir _rv_had_runfiles_dir

set auto_path $_rv_saved_auto_path

unset _rv_self _rv_tree _rv_saved_auto_path
array unset _rv_rloc_map
rename _rv_rloc {}

if {$_rv_source_status != 0} {
    unset _rv_source_status
    return -options $_rv_source_opts $_rv_source_err
}
unset _rv_source_status _rv_source_err _rv_source_opts
