"""Module extension that fetches mdbook-mermaid for `//docs`.

Produces one repository, `@mdbook_mermaid`, holding the `mdbook-mermaid`
preprocessor binary for the host platform plus the matching browser-side
`mermaid.min.js`. `//docs:book` consumes both; nothing else should.

The extension is marked reproducible: it has no inputs beyond the pinned
URLs and checksums below, so Bazel keeps it out of `MODULE.bazel.lock`.
"""

# Last mdbook-mermaid release built against the mdbook 0.4 crate, which is
# what `rules_rust_mdbook`'s toolchain ships (0.17 moved to mdbook 0.5).
_MDBOOK_MERMAID_VERSION = "0.16.2"

_MDBOOK_MERMAID_URL = "https://github.com/badboy/mdbook-mermaid/releases/download/v{version}/mdbook-mermaid-v{version}-{triple}.tar.gz"

# host key -> (release triple, sha256 of the tarball)
_MDBOOK_MERMAID_BINARIES = {
    "linux-aarch64": ("aarch64-unknown-linux-musl", "b0b01c471c93ff0e413ba9fe205884498811c74694608436c1cf9c36d2fc7e3b"),
    "linux-x86_64": ("x86_64-unknown-linux-gnu", "53212493f30f15248236b26964355fd84bd5ac66359242e42f5aa2fa8d2e4997"),
    "macos-aarch64": ("aarch64-apple-darwin", "1fc7813ea56bf3e889c3dcd13b0149ff8c7aa8d1e18530b13a0dc882f6383cc2"),
    "macos-x86_64": ("x86_64-apple-darwin", "f3b7bc35819b457cf64d63ae4c21cfff90726d12306db4be4d037ddc9a2a073b"),
}

# The renderer mdbook-mermaid 0.16.2 bundles in `mdbook-mermaid install`.
_MERMAID_JS_VERSION = "11.6.0"

_MERMAID_JS_URL = "https://cdn.jsdelivr.net/npm/mermaid@{version}/dist/mermaid.min.js"

_MERMAID_JS_SHA256 = "3a93016a73dc82ba890d919f9bbb176f3da9d98341650c0b517f2595cc68fef8"

_BUILD = """\
# Generated by //docs:extensions.bzl.
exports_files(
    [
        "mdbook-mermaid",
        "mermaid.min.js",
    ],
    visibility = ["//visibility:public"],
)
"""

def _host_key(repository_ctx):
    os_name = repository_ctx.os.name.lower()
    if os_name.startswith("linux"):
        os_key = "linux"
    elif os_name.startswith("mac"):
        os_key = "macos"
    else:
        os_key = os_name

    arch = repository_ctx.os.arch.lower()
    arch_key = {
        "aarch64": "aarch64",
        "amd64": "x86_64",
        "arm64": "aarch64",
        "x86_64": "x86_64",
    }.get(arch, arch)

    return "{}-{}".format(os_key, arch_key)

def _mdbook_mermaid_repository_impl(repository_ctx):
    host = _host_key(repository_ctx)
    if host not in _MDBOOK_MERMAID_BINARIES:
        fail("mdbook-mermaid: no prebuilt binary for host '{}' (known: {})".format(
            host,
            ", ".join(sorted(_MDBOOK_MERMAID_BINARIES.keys())),
        ))
    triple, sha256 = _MDBOOK_MERMAID_BINARIES[host]

    repository_ctx.download_and_extract(
        url = _MDBOOK_MERMAID_URL.format(version = _MDBOOK_MERMAID_VERSION, triple = triple),
        sha256 = sha256,
    )
    repository_ctx.download(
        url = _MERMAID_JS_URL.format(version = _MERMAID_JS_VERSION),
        sha256 = _MERMAID_JS_SHA256,
        output = "mermaid.min.js",
    )
    repository_ctx.file("BUILD.bazel", _BUILD)

_mdbook_mermaid_repository = repository_rule(
    doc = "Fetch the host's `mdbook-mermaid` binary and `mermaid.min.js`.",
    implementation = _mdbook_mermaid_repository_impl,
)

def _mermaid_impl(module_ctx):
    _mdbook_mermaid_repository(name = "mdbook_mermaid")
    return module_ctx.extension_metadata(
        root_module_direct_deps = [],
        root_module_direct_dev_deps = ["mdbook_mermaid"],
        reproducible = True,
    )

mermaid = module_extension(
    doc = "Fetches mdbook-mermaid and mermaid.js for the documentation build.",
    implementation = _mermaid_impl,
)
